<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="Application\BeachTennis.Application.csproj" />
    <ProjectReference Include="Infrastructure\BeachTennis.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Domain\**\*.cs;Application\**\*.cs;Infrastructure\**\*.cs" />
  </ItemGroup>

</Project>
